@extends('layouts.app')
@section('content')
<div class="title-wrapper pt-30"><div class="row align-items-center"><div class="col-md-6"><div class="title mb-30"><h2>Roles</h2></div></div><div class="col-md-6 text-end"><button class="main-btn primary-btn btn-hover" data-bs-toggle="modal" data-bs-target="#crearRol"><i class="lni lni-plus"></i> Nuevo rol</button></div></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card-styles"><div class="card-style-3 mb-30"><div class="card-content"><div class="table-wrapper table-responsive"><table class="table table-hover"><thead><tr><th>ID</th><th>Nombre</th><th>Usuarios</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
@forelse($roles as $rol)<tr><td>{{ $rol->id }}</td><td><strong>{{ $rol->name }}</strong></td><td>{{ $rol->users_count }}</td><td><span class="badge {{ $rol->name==='admin'?'bg-dark':'bg-success' }}">{{ $rol->name==='admin'?'Protegido':'Editable' }}</span></td><td>@if($rol->name!=='admin')<button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#editarRol{{ $rol->id }}" title="Editar"><i class="lni lni-pencil"></i></button>@else<span class="text-muted">Sin cambios</span>@endif</td></tr>
@empty<tr><td colspan="5" class="text-center">No hay roles registrados.</td></tr>@endforelse
</tbody></table></div></div></div></div>
<div class="modal fade" id="crearRol" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('configuraciones.roles.store') }}">@csrf<div class="modal-header"><h5 class="modal-title">Nuevo rol</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Nombre</label><input class="form-control" name="name" value="{{ old('name') }}" required></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Crear</button></div></form></div></div></div>
@foreach($roles->where('name','!=','admin') as $rol)<div class="modal fade" id="editarRol{{ $rol->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('configuraciones.roles.update',$rol) }}">@csrf @method('PUT')<div class="modal-header"><h5 class="modal-title">Editar rol</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Nombre</label><input class="form-control" name="name" value="{{ $rol->name }}" required></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary">Guardar</button></div></form></div></div></div>@endforeach
@endsection
