services:
  - type: web
    name: restaurante-laravel
    env: docker
    plan: free
    rootDir: sistema-web
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Las Brazas
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: es
      - key: APP_TIMEZONE
        value: America/La_Paz
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
