<div class="row g-3">
<div class="col-md-6"><label class="form-label">Nombre de la presentacion</label><input class="form-control" name="nombre" value="{{ old('nombre',$presentacion?->nombre) }}" required></div>
<div class="col-md-3"><label class="form-label">Categoria</label><select class="form-select" name="categoria_id" required>@foreach($categorias as $categoria)<option value="{{ $categoria->id }}" @selected(old('categoria_id',$presentacion?->categoria_id??$insumo->categoria_id)==$categoria->id)>{{ $categoria->nombre }}</option>@endforeach</select></div>
<div class="col-md-3"><label class="form-label">Uso</label><select class="form-select" name="tipo_uso" required><option value="indirecto" @selected(old('tipo_uso',$presentacion?->tipo_uso??'indirecto')==='indirecto')>Indirecto</option><option value="directo" @selected(old('tipo_uso',$presentacion?->tipo_uso)==='directo')>Directo</option><option value="mixto" @selected(old('tipo_uso',$presentacion?->tipo_uso)==='mixto')>Mixto</option></select></div>
<div class="col-12"><label class="form-label">Descripcion</label><textarea class="form-control" name="descripcion" rows="2">{{ old('descripcion',$presentacion?->descripcion) }}</textarea></div>
<div class="col-md-3"><label class="form-label">Unidad de control del stock</label><select class="form-select" name="unidad_stock_id" required>@foreach($unidades as $unidad)<option value="{{ $unidad->id }}" @selected(old('unidad_stock_id',$presentacion?->unidad_stock_id??$insumo->unidad_medida_id)==$unidad->id)>{{ $unidad->nombre }} ({{ $unidad->abreviatura }})</option>@endforeach</select><small class="text-muted">Medida real: kg, litro, unidad, arroba, etc.</small></div>
<div class="col-md-3"><label class="form-label">Stock minimo</label><input type="number" class="form-control" name="stock_minimo" min="0" step="0.0001" value="{{ old('stock_minimo',$presentacion?->stock_minimo??0) }}" required></div>
<div class="col-md-3"><label class="form-label">Costo estandar automatico</label><div class="input-group"><span class="input-group-text">Bs.</span><input class="form-control" value="{{ $presentacion?->costo_estandar!==null?number_format($presentacion->costo_estandar,4,'.',''):'' }}" placeholder="Se calcula al recibir compras" readonly></div></div>
<div class="col-md-4"><label class="form-label">Empaque o formato</label><select class="form-select" name="formato_empaque_id"><option value="">Sin definir</option>@foreach($formatos as $formato)<option value="{{ $formato->id }}" @selected(old('formato_empaque_id',$presentacion?->formato_empaque_id)==$formato->id)>{{ $formato->nombre }}</option>@endforeach</select><small class="text-muted">Como viene el insumo. Elige "A granel" si no tiene empaque fijo.</small></div>
<div class="col-md-4"><label class="form-label">Contenido</label><input type="number" class="form-control" name="contenido" min="0.0001" step="0.0001" value="{{ old('contenido',$presentacion?->contenido) }}" placeholder="Opcional"><small class="text-muted">Solo si el empaque contiene una cantidad fija.</small></div>
<div class="col-md-4"><label class="form-label">Unidad de medida del contenido</label><select class="form-select" name="unidad_contenido_id"><option value="">Seleccionar</option>@foreach($unidades as $unidad)<option value="{{ $unidad->id }}" @selected(old('unidad_contenido_id',$presentacion?->unidad_contenido_id)==$unidad->id)>{{ $unidad->nombre }}</option>@endforeach</select><small class="text-muted">Ej. kg, litros o unidades. No es caja ni bolsa.</small></div>
<div class="col-md-6"><label class="form-label">Imagen</label><input type="file" class="form-control" name="imagen" accept="image/*"></div><div class="col-md-6"><label class="form-label">Codigo de barras</label><input class="form-control" name="codigo_barras" value="{{ old('codigo_barras',$presentacion?->codigo_barras) }}"></div>
<div class="col-12 d-flex gap-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="retornable" value="1" @checked(old('retornable',$presentacion?->retornable))> Retornable</label><label class="form-check"><input class="form-check-input" type="checkbox" name="predeterminada" value="1" @checked(old('predeterminada',$presentacion?->predeterminada??!$insumo->presentaciones()->exists()))> Predeterminada</label><label class="form-check"><input class="form-check-input" type="checkbox" name="activa" value="1" @checked(old('activa',$presentacion?->activa??true))> Activa</label></div>
</div>
