@csrf
@if($menuDia) @method('PUT') @endif
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Titulo</label><input class="form-control" name="titulo" value="{{ old('titulo',$menuDia?->titulo) }}" required></div>
    <div class="col-md-3"><label class="form-label">Tipo de comida</label><select class="form-select" name="tipo_comida_id"><option value="">General</option>@foreach($tiposComida as $tipo)<option value="{{ $tipo->id }}" @selected(old('tipo_comida_id',$menuDia?->tipo_comida_id)==$tipo->id)>{{ $tipo->nombre }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Fecha</label><input type="date" class="form-control" name="fecha" value="{{ old('fecha',$fechaPredefinida) }}" required></div>
    <div class="col-md-3"><label class="form-label">Hora inicio</label><input type="time" class="form-control" name="hora_inicio" value="{{ old('hora_inicio',substr((string)$menuDia?->hora_inicio,0,5)) }}"></div>
    <div class="col-md-3"><label class="form-label">Hora fin</label><input type="time" class="form-control" name="hora_fin" value="{{ old('hora_fin',substr((string)$menuDia?->hora_fin,0,5)) }}"></div>
    <div class="col-md-3 d-flex align-items-end"><label class="form-check"><input type="checkbox" class="form-check-input" name="visible_para_clientes" value="1" @checked(old('visible_para_clientes',$menuDia?->visible_para_clientes))> Visible para clientes</label></div>
    <div class="col-md-3 d-flex align-items-end"><label class="form-check"><input type="checkbox" class="form-check-input" name="visible_en_horario" value="1" @checked(old('visible_en_horario',$menuDia?->visible_en_horario))> Aplicar horario</label></div>
    <div class="col-12"><label class="form-label">Descripcion</label><textarea class="form-control" name="descripcion">{{ old('descripcion',$menuDia?->descripcion) }}</textarea></div>
</div>
<section class="border-top mt-4 pt-4"><h4 class="mb-3">Platos</h4><div class="row">
@foreach($recetas as $receta)<div class="col-md-6 col-lg-4 mb-3"><div class="border rounded p-3 h-100"><label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="recetas[]" value="{{ $receta->id }}" @checked(in_array($receta->id,old('recetas',$seleccionadas)))> <strong>{{ $receta->nombre }}</strong></label><label class="small">Tipo de produccion</label><select class="form-select mb-2" name="tipos_produccion_recetas[{{ $receta->id }}]"><option value="">Sin grupo</option>@foreach($tiposProduccion as $tipo)<option value="{{ $tipo->id }}" @selected(old('tipos_produccion_recetas.'.$receta->id,$tiposRecetas[$receta->id]??null)==$tipo->id)>{{ $tipo->nombre }}</option>@endforeach</select><label class="small">Cantidad</label><input type="number" min="1" class="form-control" name="cantidades[{{ $receta->id }}]" value="{{ old('cantidades.'.$receta->id,$cantidades[$receta->id]??1) }}"></div></div>@endforeach
</div></section>
@if($presentacionesDirectas->isNotEmpty())<section class="border-top mt-3 pt-4"><h4 class="mb-3">Productos directos</h4><div class="row">
@foreach($presentacionesDirectas as $presentacion)@php($imagen=$presentacion->imagen?asset('storage/'.$presentacion->imagen):($presentacion->insumo->imagen?asset('storage/'.$presentacion->insumo->imagen):null))<div class="col-md-6 col-lg-4 mb-3"><div class="border rounded p-3 h-100">@if($imagen)<img src="{{ $imagen }}" alt="{{ $presentacion->nombre_completo }}" class="mb-2" style="width:56px;height:56px;object-fit:cover;border-radius:6px">@endif<label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="presentaciones_directas[]" value="{{ $presentacion->id }}" @checked(in_array($presentacion->id,old('presentaciones_directas',$presentacionesSeleccionadas)))> <strong>{{ $presentacion->nombre_completo }}</strong></label><label class="small">Tipo de produccion</label><select class="form-select mb-2" name="tipos_produccion_presentaciones[{{ $presentacion->id }}]"><option value="">Sin grupo</option>@foreach($tiposProduccion as $tipo)<option value="{{ $tipo->id }}" @selected(old('tipos_produccion_presentaciones.'.$presentacion->id,$tiposPresentaciones[$presentacion->id]??null)==$tipo->id)>{{ $tipo->nombre }}</option>@endforeach</select><label class="small">Cantidad disponible</label><input type="number" min="1" class="form-control mb-2" name="cantidades_presentaciones[{{ $presentacion->id }}]" value="{{ old('cantidades_presentaciones.'.$presentacion->id,$cantidadesPresentaciones[$presentacion->id]??1) }}"><label class="small">Precio de venta (Bs.)</label><input type="number" min="0" step="0.01" class="form-control" name="precios_presentaciones[{{ $presentacion->id }}]" value="{{ old('precios_presentaciones.'.$presentacion->id,$preciosPresentaciones[$presentacion->id]??'') }}"></div></div>@endforeach
</div></section>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<button class="btn btn-primary"><i class="lni lni-save"></i> Guardar menu</button> <a href="{{ route('menus-dia.index') }}" class="btn btn-secondary">Cancelar</a>
