@extends('layouts.app')
@section('content')
<div class="title-wrapper pt-30"><div class="row"><div class="col-md-8"><div class="title mb-30"><h2>{{ $menuDia->titulo }}</h2></div></div><div class="col-md-4 text-end"><a class="btn btn-warning" href="{{ route('menus-dia.edit',$menuDia) }}"><i class="lni lni-pencil"></i> Editar</a></div></div></div>
<div class="card-style-3 mb-30"><div class="card-content">@php
[$estadoPublicacion,$clasePublicacion]=$menuDia->estadoPublicacion();
$grupos=collect();
@endphp
<div class="row mb-4"><div class="col-md-3"><strong>Fecha</strong><p>{{ $menuDia->fecha->format('d/m/Y') }}</p></div><div class="col-md-3"><strong>Tipo</strong><p>{{ $menuDia->tipoComida?->nombre?:'General' }}</p></div><div class="col-md-3"><strong>Horario</strong><p>{{ substr((string)$menuDia->hora_inicio,0,5)?:'-' }} - {{ substr((string)$menuDia->hora_fin,0,5)?:'-' }}</p></div><div class="col-md-3"><strong>Estado</strong><p><span class="badge {{ $clasePublicacion }}">{{ $estadoPublicacion }}</span></p></div></div>
@php
$leerAdiciones=fn($valor)=>is_array($valor)?$valor:(json_decode((string)$valor,true)?:[]);
$elementos=$menuDia->recetas->map(function($r)use($leerAdiciones){$adiciones=array_values(array_filter(array_map('intval',$leerAdiciones($r->pivot->adiciones??null)),fn($n)=>$n>0));$inicial=(int)$r->pivot->cantidad_inicial;$total=$inicial+array_sum($adiciones);return ['tipo_id'=>$r->pivot->tipo_produccion_id,'nombre'=>$r->nombre,'precio'=>$r->pivot->precio_venta??$r->precio,'inicial'=>$inicial,'adiciones'=>$adiciones,'total'=>$total,'disponible'=>(int)$r->pivot->cantidad];})->concat($menuDia->presentacionesDirectas->map(function($p)use($leerAdiciones){$adiciones=array_values(array_filter(array_map('intval',$leerAdiciones($p->pivot->adiciones??null)),fn($n)=>$n>0));$inicial=(int)$p->pivot->cantidad_inicial;$total=$inicial+array_sum($adiciones);return ['tipo_id'=>$p->pivot->tipo_produccion_id,'nombre'=>$p->nombre_completo,'precio'=>$p->pivot->precio_venta,'inicial'=>$inicial,'adiciones'=>$adiciones,'total'=>$total,'disponible'=>(int)$p->pivot->cantidad];}));
$grupos=$elementos->groupBy(fn($e)=>(string)($e['tipo_id']??'otros'));
@endphp
@foreach($tiposProduccion as $tipo)@if($grupos->has((string)$tipo->id))<section class="border-top pt-3 mt-3"><h4 class="mb-3">{{ $tipo->nombre }}</h4><div class="table-responsive"><table class="table"><thead><tr><th>Producto ofrecido</th><th>Precio</th><th>Inicial</th><th>Adiciones</th><th>Produccion total</th><th>Disponible</th><th>Vendido</th></tr></thead><tbody>@foreach($grupos->get((string)$tipo->id) as $item)<tr><td><strong>{{ $item['nombre'] }}</strong></td><td>Bs {{ number_format($item['precio'],2) }}</td><td>{{ $item['inicial'] }}</td><td>@forelse($item['adiciones'] as $adicion)<span class="badge bg-success me-1">+{{ $adicion }}</span>@empty - @endforelse</td><td>{{ $item['total'] }}</td><td>{{ $item['disponible'] }}</td><td>{{ max(0,$item['total']-$item['disponible']) }}</td></tr>@endforeach</tbody></table></div></section>@endif @endforeach
@if($grupos->has('otros'))<section class="border-top pt-3 mt-3"><h4 class="mb-3">Otros</h4><div class="table-responsive"><table class="table"><thead><tr><th>Producto ofrecido</th><th>Precio</th><th>Inicial</th><th>Adiciones</th><th>Produccion total</th><th>Disponible</th><th>Vendido</th></tr></thead><tbody>@foreach($grupos->get('otros') as $item)<tr><td><strong>{{ $item['nombre'] }}</strong></td><td>Bs {{ number_format($item['precio'],2) }}</td><td>{{ $item['inicial'] }}</td><td>@forelse($item['adiciones'] as $adicion)<span class="badge bg-success me-1">+{{ $adicion }}</span>@empty - @endforelse</td><td>{{ $item['total'] }}</td><td>{{ $item['disponible'] }}</td><td>{{ max(0,$item['total']-$item['disponible']) }}</td></tr>@endforeach</tbody></table></div></section>@endif
<hr class="my-4"><h5>Historial del menu</h5><div class="table-responsive"><table class="table"><thead><tr><th>Fecha y hora</th><th>Usuario</th><th>Accion</th><th>Detalles</th></tr></thead><tbody>@forelse(array_reverse($menuDia->historial??[]) as $entrada)<tr><td>{{ isset($entrada['fecha'])?\Carbon\Carbon::parse($entrada['fecha'])->timezone(config('app.timezone'))->format('d/m/Y H:i'):'-' }}</td><td>{{ $entrada['usuario']??'Sistema' }}</td><td><strong>{{ $entrada['accion']??'Cambio' }}</strong></td><td>{{ $entrada['detalles']??'-' }}</td></tr>@empty<tr><td colspan="4" class="text-center">Sin movimientos registrados.</td></tr>@endforelse</tbody></table></div>
</div></div>
@endsection

