@extends('layouts.app')
@section('content')
<div class="title-wrapper pt-30"><div class="row align-items-center"><div class="col-md-7"><div class="title mb-30"><h2>Formatos de empaque</h2></div></div>@can('formatos_empaque.crear')<div class="col-md-5 text-end"><button class="main-btn primary-btn mb-30" data-bs-toggle="modal" data-bs-target="#crearFormato"><i class="lni lni-plus"></i> Nuevo formato</button></div>@endcan</div></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card-style-3 mb-30"><div class="card-content"><p class="text-muted mb-3">Define formas generales como caja, bolsa o botella. La cantidad que contiene cada una se configura dentro de la presentación del insumo.</p><div class="table-responsive"><table class="table"><thead><tr><th>Formato</th><th>Descripción</th><th>Unidad relacionada</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>
@forelse($formatos as $formato)<tr><td><strong>{{ $formato->nombre }}</strong>@if($formato->es_granel)<br><small class="text-muted">Sin empaque fijo</small>@endif</td><td>{{ $formato->descripcion?:'-' }}</td><td>{{ $formato->unidadMedida?->nombre?:'No necesita' }}</td><td><span class="badge {{ $formato->activo?'bg-success':'bg-secondary' }}">{{ $formato->activo?'Activo':'Inactivo' }}</span></td><td>@can('formatos_empaque.editar')<button class="btn btn-warning btn-sm" data-bs-toggle="modal" data-bs-target="#editarFormato{{ $formato->id }}"><i class="lni lni-pencil"></i></button>@endcan @can('formatos_empaque.eliminar')<form class="d-inline" method="POST" action="{{ route('formatos-empaque.destroy',$formato) }}" onsubmit="return confirm('Eliminar este formato?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="lni lni-trash-can"></i></button></form>@endcan</td></tr>@empty<tr><td colspan="5" class="text-center">No hay formatos registrados.</td></tr>@endforelse
</tbody></table></div></div></div>
@can('formatos_empaque.crear')<div class="modal fade" id="crearFormato"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('formatos-empaque.store') }}">@csrf<div class="modal-header"><h5>Nuevo formato</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('formatos-empaque.form',['formato'=>null])</div><div class="modal-footer"><button class="btn btn-primary">Guardar</button></div></form></div></div></div>@endcan
@can('formatos_empaque.editar')@foreach($formatos as $formato)<div class="modal fade" id="editarFormato{{ $formato->id }}"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('formatos-empaque.update',$formato) }}">@csrf @method('PUT')<div class="modal-header"><h5>Editar formato</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('formatos-empaque.form',['formato'=>$formato])</div><div class="modal-footer"><button class="btn btn-primary">Guardar</button></div></form></div></div></div>@endforeach @endcan
@endsection

